#!/bin/bash

set -e

echo "Validating Nginx configuration..."

sudo nginx -t

echo "Starting Nginx..."

sudo systemctl enable nginx
sudo systemctl restart nginx

echo "Checking Nginx service..."

sudo systemctl is-active --quiet nginx

echo "Nginx is running successfully."
